blueprint:
  name: Paralelo Virtual TomTech (Anti-Loop)
  description: Sincroniza switches/lights sem loops, ignorando o dispositivo que iniciou a ação.
  domain: automation

  input:
    dispositivos:
      name: Selecionar Dispositivos
      description: Escolha todos os switches e lights que devem atuar em paralelo.
      selector:
        entity:
          domain:
            - switch
            - light
          multiple: true

mode: restart
max_exceeded: silent

trigger:
  - platform: state
    entity_id: !input dispositivos

variables:
  origem: "{{ trigger.entity_id }}"
  estado: "{{ trigger.to_state.state }}"
  grupo: !input dispositivos
  destino: "{{ grupo | reject('equalto', origem) | list }}"

action:
  - choose:
      - conditions: "{{ estado == 'on' }}"
        sequence:
          - service: homeassistant.turn_on
            target:
              entity_id: "{{ destino }}"

      - conditions: "{{ estado == 'off' }}"
        sequence:
          - service: homeassistant.turn_off
            target:
              entity_id: "{{ destino }}"

  - delay: "00:00:01"
