blueprint:
  name: Paralelo Virtual (Compatível Universal)
  description: Sincroniza múltiplos switches/lâmpadas como paralelo virtual.
  domain: automation

  input:
    entidades:
      name: Entidades do paralelo
      selector:
        entity:
          multiple: true
          domain:
            - switch
            - light

trigger:
  platform: state
  entity_id: !input entidades

action:
  - service: >
      {% if trigger.to_state.state == 'on' %}
        homeassistant.turn_on
      {% else %}
        homeassistant.turn_off
      {% endif %}
    data:
      entity_id: >
        {% set origem = trigger.entity_id %}
        {% set todos = expand(inputs.entidades) | map(attribute='entity_id') | list %}
        {{ todos | reject('equalto', origem) | list }}

mode: restart
