blueprint:
  name: Paralelo Virtual (Compatível e Anti-Loop)
  description: Sincroniza switches/lâmpadas como se estivessem em paralelo físico.
  domain: automation

  input:
    entidades:
      name: Entidades do paralelo
      selector:
        entity:
          multiple: true
          domain:
            - switch
            - light

trigger:
  platform: state
  entity_id: !input entidades

action:

  # 1. Calcula dinamicamente quem deve receber o comando
  - set:
      destino: >
        {% set todos = expand( inputs.entidades ) %}
        {% set origem = trigger.entity_id %}
        {{ todos | map(attribute='entity_id') | reject('equalto', origem) | list }}

  # 2. Executa ON
  - choose:
      - conditions: "{{ trigger.to_state.state == 'on' }}"
        sequence:
          - service: homeassistant.turn_on
            data:
              entity_id: "{{ destino }}"

  # 3. Executa OFF
      - conditions: "{{ trigger.to_state.state == 'off' }}"
        sequence:
          - service: homeassistant.turn_off
            data:
              entity_id: "{{ destino }}"

mode: queued
max: 5
