blueprint:
  name: Paralelo Virtual TomTech (Blindado)
  description: Sincroniza entidades sem loop, com debounce e trava de execução.
  domain: automation

  input:
    dispositivos:
      name: Selecionar Dispositivos
      selector:
        entity:
          domain: 
            - switch
            - light
          multiple: true

mode: restart
max_exceeded: silent

trigger:
  - platform: state
    entity_id: !input dispositivos

variables:
  grupo: !input dispositivos
  origem: "{{ trigger.entity_id }}"
  estado: "{{ trigger.to_state.state }}"
  destino: "{{ grupo | reject('equalto', origem) | list }}"

action:
  # ------ PROTEÇÃO 1 – DEBOUNCE ------
  - wait_for_trigger:
      - platform: state
        entity_id: "{{ origem }}"
    timeout: "00:00:00.3"
    continue_on_timeout: true

  # ------ PROTEÇÃO 2 – LOCK ------
  - condition: >
      {{ not is_state('automation.' ~ this.entity_id.split('.')[1], 'off') }}

  # ------ EXECUÇÃO PRINCIPAL ------
  - choose:
      - conditions: "{{ estado == 'on' }}"
        sequence:
          - service: homeassistant.turn_on
            target:
              entity_id: "{{ destino }}"

      - conditions: "{{ estado == 'off' }}"
        sequence:
          - service: homeassistant.turn_off
            target:
              entity_id: "{{ destino }}"

  # Pequeno delay para estabilização dos estados
  - delay: "00:00:00.4"
