blueprint:
  name: Paralelo Virtual (Compatível e Anti-Loop Final)
  description: Sincroniza switches/lâmpadas como paralelo virtual, sem loop e compatível com todas as versões.
  domain: automation

  input:
    entidades:
      name: Entidades que farão parte do paralelo
      selector:
        entity:
          multiple: true
          domain:
            - switch
            - light

trigger:
  platform: state
  entity_id: !input entidades

action:
  - choose:
      - conditions: "{{ trigger.to_state.state == 'on' }}"
        sequence:
          - service: homeassistant.turn_on
            data:
              entity_id: >
                {% set origem = trigger.entity_id %}
                {% set todos = expand(inputs.entidades) | map(attribute='entity_id') | list %}
                {{ todos | reject('equalto', origem) | list }}

      - conditions: "{{ trigger.to_state.state == 'off' }}"
        sequence:
          - service: homeassistant.turn_off
            data:
              entity_id: >
                {% set origem = trigger.entity_id %}
                {% set todos = expand(inputs.entidades) | map(attribute='entity_id') | list %}
                {{ todos | reject('equalto', origem) | list }}

mode: queued
max: 5
