blueprint:
  name: Paralelo Virtual (Seguro e Anti-Loop)
  description: Sincroniza múltiplos switches/lâmpadas como um único paralelo virtual, sem loop.
  domain: automation

  input:
    entidades:
      name: Entidades que farão parte do paralelo
      selector:
        entity:
          multiple: true
          domain:
            - switch
            - light

trigger:
  platform: state
  entity_id: !input entidades

variables:
  todas: !input entidades
  origem: "{{ trigger.entity_id }}"
  destino: "{{ expand(todas) | map(attribute='entity_id') | reject('equalto', origem) | list }}"

action:
  - choose:
      - conditions: "{{ destino | length > 0 }}"
        sequence:
          - service: >
              {% if trigger.to_state.state == "on" %}
                homeassistant.turn_on
              {% else %}
                homeassistant.turn_off
              {% endif %}
            target:
              entity_id: "{{ destino }}"

mode: queued
max: 10
