blueprint:
  name: Paralelo Virtual (Compatível e Anti-Loop)
  description: Sincroniza múltiplos switches/lâmpadas como se estivessem em paralelo, sem loop.
  domain: automation

  input:
    entidades:
      name: Entidades do paralelo virtual
      selector:
        entity:
          multiple: true
          domain:
            - switch
            - light

trigger:
  platform: state
  entity_id: !input entidades

variables:
  todas: !input entidades
  origem: "{{ trigger.entity_id }}"
  destino: >
    {{ expand(todas)
        | map(attribute='entity_id')
        | reject('equalto', origem)
        | list }}

action:

  - variables:
      estado_atual: "{{ trigger.to_state.state }}"

  - choose:
      - conditions: "{{ destino | length > 0 }}"
        sequence:

          - service: homeassistant.turn_on
            data:
              entity_id: >
                {% if estado_atual == 'on' %}
                  {{ destino }}
                {% endif %}

          - service: homeassistant.turn_off
            data:
              entity_id: >
                {% if estado_atual == 'off' %}
                  {{ destino }}
                {% endif %}

mode: queued
max: 5
